unbuffered-read: unbuffered_read.c
	gcc -g -std=gnu11 unbuffered_read.c -o unbuffered_read

unbuffered-write: unbuffered-write.c
	gcc -g -std=gnu11 unbuffered-write.c -o unbuffered-write

buffered-write: write-buffer.c
	gcc -g -std=gnu11 write-buffer.c -o write-buffer

buffered-read: read-buffer.c
	gcc -g -std=gnu11 read-buffer.c -o read-buffer