#include "the_apple.h"

char* apple = "                     a\n"
              "                    ppl\n"
              "                  eappl\n"
              "                 eapple\n"
              "                 apple\n"
              "                 appl\n"
              "         eappleappleappleappl\n"
              "    eappleappleappleappleapple\n"
              "   appleappleappleappleappleapple\n"
              "  appleappleappleappleappleappleappl\n"
              " eappleappleappleappleappleappleapple\n"
              "appleappleappleappleappleappleappleapp\n"
              "leappleappleappleappleappleappleapplea\n"
              "ppleappleappleappleappleappleappleappl\n"
              "eappleappleappleappleappleappleappleap\n"
              "pleappleappleappleappleappleappleapple\n"
              "appleappleappleappleappleappleappleapp\n"
              "leappleappleappleappwormpleappleapplea\n"
              " ppleappleappleappleappleappleappleap\n"
              "  pleappleappleappleappleappleapplea\n"
              "   ppleappleappleappleappleappleapp\n"
              "   leappleappleappleappleappleap\n"
              "     pleappleappleappleappleapp\n"
              "       leappleappleappleapple\n"
              "         appleappleappleapp\n";


